version: '3.9'

services:

  database:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_USER: almaz

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080